# permissions for end users to view gardenerclusterprovisioningrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gardenerclusterprovisioningrequest-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: infrastructure-manager
    app.kubernetes.io/part-of: infrastructure-manager
    app.kubernetes.io/managed-by: kustomize
  name: gardenerclusterprovisioningrequest-viewer-role
rules:
- apiGroups:
  - infrastructuremanager.kyma-project.io
  resources:
  - gardenerclusterprovisioningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructuremanager.kyma-project.io
  resources:
  - gardenerclusterprovisioningrequests/status
  verbs:
  - get
