---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infrastructure-manager-role
  namespace: kcp-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - infrastructuremanager.kyma-project.io
  resources:
  - gardenerclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructuremanager.kyma-project.io
  resources:
  - gardenerclusters/finalizers
  - gardenerclusters/status
  - runtimes/finalizers
  - runtimes/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - infrastructuremanager.kyma-project.io
  resources:
  - runtimes
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
