apiVersion: infrastructuremanager.kyma-project.io/v1
kind: GardenerClusterProvisioningRequest
metadata:
  labels:
    kyma-project.io/instance-id: instance-id
    kyma-project.io/runtime-id: runtime-id
    kyma-project.io/broker-plan-id: plan-id
    kyma-project.io/broker-plan-name: plan-name
    kyma-project.io/global-account-id: global-account-id
    kyma-project.io/subaccount-id: subAccount-id
    kyma-project.io/shoot-name: shoot-name
    kyma-project.io/region: region
    operator.kyma-project.io/kyma-name: kymaName
  name: runtime-id
  namespace: kcp-system
spec:
  shoot:
    name: shoot-name
    # There is an ongoing effort in Gardener to change the dns object semantics the spec.dns will contain primary provider only, the additional ones will be specified in the extension's config). Please see: https://github.com/gardener/gardener/issues/9176
    # We can follow DNS object structure from the Gardener as we can assume the backward compatibility (please see the above ticket)
    # If the dns object is not set the defaults will be used
    dns:
      domain: mycool.domain.com
      providers:
      - domains:
        include:
          - mycool.domain.com
        primary: true
        # If the secret is not set default secret will be used
        secretName: domain-names-secret
        type: aws-route53
    kubernetes:
      version: "1.28.7"
      kubeAPIServer:
        auditConfig:
          # This is optional. If additional Audit Policy is specified it will be merged with default one.
          # If the additional Audit Policy is specified KIM will create a config map with the merged policy, and pass it to the Gardener
          additionalAuditPolicy: |
            - level: Request
                resources:
                - group: "my.cool.group.io"
                - group: "some.other.group.io"
        # spec.shoot.kubernetes.kubeAPIServer.oidcConfig was added to meet the following requirement: https://github.com/kyma-project/kyma/issues/18305
        # the object will be passed by KEB, if not specified defaults will be set
        # It follows the structure of the shoot spec, and allows creating [OpenIDConnect CR](https://github.com/gardener/gardener-extension-shoot-oidc-service/blob/5fd98637da01deb3f7a99403cd893ee86acd26a8/example/40-openidconnect.yaml#L8)
        # TODO: when registering new provider KIM also needs to specify permissions for the accounts authenticated by the new provider.
        oidcConfig:
          clientID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
          groupsClaim: groups
          issuerURL: https://my.cool.tokens.com
          signingAlgs:
          - RS256
          usernameClaim: sub
          usernamePrefix: '-'
    # spec.shoot.provider was added to meet the following requirements:
    # - https://github.com/kyma-project/infrastructure-manager/issues/46
    # - https://github.com/kyma-project/kyma/issues/18195
   # It follows the structure of the shoot spec (Provider struct from https://github.com/gardener/gardener/blob/master/pkg/apis/core/types_shoot.go)
    provider:
      type: gcp
      purpose: evaluation
      region: eu-central-1
      # this field is not obligatory
      # if not provided the KIM will use HAP to provide secretBindingName
      secretBindingName: "some secret"
      seedName: aws-eu5
      controlPlaneConfig:
        apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
        kind: ControlPlaneConfig
        zone: us-central1-b
      infrastructureConfig:
        apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
        kind: InfrastructureConfig
        networks:
          worker: 10.250.0.0/22
          workers: 10.250.0.0/22
      workers:
        - cri:
            name: containerd
          name: worker-klbc9
          machine:
            type: n1-standard-2
            image:
              name: gardenlinux
              version: 1312.3.0
            architecture: amd64
          maximum: 2
          minimum: 1
          maxSurge: 1
          maxUnavailable: 0
          volume:
            type: pd-balanced
            size: 50Gi
          zones:
            - europe-west1-d
  kubeconfig:
    secret:
      name: kubeconfig-runtime-id
      namespace: kcp-system
      key: "config"
