name: tests

on: [push, pull_request]

permissions:
  contents: read
jobs:
 # lint:
############################################################################################
  unit-tests:
    runs-on: ubuntu-latest
    steps:
############################################################################################
    - name: Checkout code
      uses: actions/checkout@v4
############################################################################################
    - name: Set up cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          /home/runner/work/infrastructure-manager/infrastructure-manager/bin
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
############################################################################################
    - name: Set up go environment
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.2
############################################################################################
    - name: Run unit tests
      run: make test
